@apiUri = https://f645hjkzq8.execute-api.ap-northeast-1.amazonaws.com/v1

# @name login
POST https://cognito-idp.ap-northeast-1.amazonaws.com/ HTTP/1.1
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{
    "AuthFlow": "USER_PASSWORD_AUTH",
    "ClientId": "4b5e7i4g71rlof7n3rae4klk36",
    "AuthParameters": {
        "USERNAME": "testuser",
        "PASSWORD": "P@ssw0rd!"
    }
}

######### collection 

### @name collection-post
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}


POST {{ apiUri }}/todos
Authorization: {{ authToken }}
Content-Type: application/json

{
    "title": "todo title testdata" ,
    "content": "todo content testdata"
}

### @name collection-get
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}

GET {{ apiUri }}/todos
Authorization: {{ authToken }}


######### object todo

### @name object-delete
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}
@delete-todo-id = 1644992109.312936
DELETE  {{ apiUri }}/todos/{{ delete-todo-id }}
Authorization: {{ authToken }}



### @name object-get
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}
@get-todo-id = 1644992044.337332
GET {{ apiUri }}/todos/{{ get-todo-id }}
Authorization: {{ authToken }}



### @name object-put(update)
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}
@put-todo-id = 1644992044.337332

PUT {{ apiUri }}/todos/{{ get-todo-id }}
Authorization: {{ authToken }}
Content-Type: application/json

{
    "title": "updated todo title testdataa" ,
    "content": "updated content testdata" ,
    "status": "todo"
}



### @name objects-patch
@authToken = {{ login.response.body.$.AuthenticationResult.IdToken }}
@patch-todo-id = 1644992044.337332

PATCH {{ apiUri }}/todos/{{ patch-todo-id }}
Authorization: {{ authToken }}
Content-Type: application/json

{
    "status": "in-progress"
}